### ISSUE TITLE
get_nom_traj(data.params,get_flats(0)) - Function Not Found

### ISSUE THREAD

**Issue by abdul-mannan-khan** [vkotaru/quad_geometric_control#3]
Venkata Naga Prasanth Kotaru.

While going through the simulation, I found that `get_nom_traj(data.params,get_flats(0))` is not in the file. It will be highly appreciable if you could please add that one. 

I am developing deep interest in your research after going through the research paper and your simulation. It is really helpful for the beginners who are new in Geometric Control. 

I am very thankful to your for your support. 

Best Regards,
Dr. Abdul Manan Khan

**Comment by MAminSFV** [comment]
I am having the same issue. Is it supposed to be the initial condition of a predefined trajectory?
It isn't very clear since there are used state variables from the Zero position section of the code.

I commented on Zero Initial Error- Configuration lines and then ran into another error in flat2state.m. There is a function named dot2 in line 23 that is unrecognized. Is it a typo or a specific convention for dot product? I guess they must be part of the geometric toolbox that is not included.

This is my first encounter with Geometric controllers in code, and I really appreciate your work and support.

**Comment by vkotaru** [comment]
Check the latest commit.
